CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR2(20) NOT NULL,
    table_name VARCHAR2(50) NOT NULL,
    user_name VARCHAR2(50) NOT NULL,
    operation_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) NOT NULL,
    error_message VARCHAR2(500)
);