CREATE TABLE diseases (
    disease_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_type VARCHAR2(50) NOT NULL,
    symptom_keywords VARCHAR2(300) NOT NULL,
    disease_name VARCHAR2(100) NOT NULL,
    treatment VARCHAR2(500) NOT NULL,
    risk_level VARCHAR2(10) CHECK (risk_level IN ('NORMAL','HIGH'))
);