CREATE TABLE crop_report (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id NUMBER NOT NULL,
    crop_type VARCHAR2(50) NOT NULL,
    symptoms VARCHAR2(500) NOT NULL,
    report_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_crop_farmer FOREIGN KEY (farmer_id) REFERENCES farmer(farmer_id)
);