CREATE TABLE alert_log (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id NUMBER NOT NULL,
    disease_id NUMBER,
    alert_status VARCHAR2(20) NOT NULL,
    severity VARCHAR2(10),
    alert_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_alert_report FOREIGN KEY (report_id) REFERENCES crop_report(report_id),
    CONSTRAINT fk_alert_disease FOREIGN KEY (disease_id) REFERENCES diseases(disease_id)
);